-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJqTjCGa/DYdlx3h1
YFXvDN/PLh04sI/lzOziFWdBLUegCgYIKoZIzj0DAQehRANCAATFD6Bm6kuCY7xg
vry/swTx9NoTUzd+vYBVj0AM8yn3Mp5ilAD5/qKxrjuICjflpOz8OyUAv3mbMmIT
K32SmtQh
-----END PRIVATE KEY-----