import 'package:flutter/cupertino.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../theme/app_colors.dart';
import '../theme/app_text_styles.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  static const _sections = [
    _PolicySection(
      title: null,
      body:
          'Effective date: 2026 April\n\n'
          'Developer ("us", "we", or "our") operates the Aviary Canvas mobile application '
          '(hereinafter referred to as the "Service"). This page informs you of our policies '
          'regarding the collection, use, and disclosure of personal data when you use our '
          'Service and the choices you have associated with that data. We use your data to '
          'provide and improve the Service. By using the Service, you agree to the collection '
          'and use of information in accordance with this policy. Unless otherwise defined in '
          'this Privacy Policy, the terms used in this Privacy Policy have the same meanings '
          'as in our Terms and Conditions.',
    ),
    _PolicySection(
      title: 'Definitions',
      body:
          'Service — the Aviary Canvas mobile application operated by Developer.\n\n'
          'Personal Data — data about a living individual who can be identified from those data '
          '(or from those and other information either in our possession or likely to come into '
          'our possession).\n\n'
          'Usage Data — data collected automatically either generated by the use of the Service '
          'or from the Service infrastructure itself (for example, the duration of a page visit).\n\n'
          'Cookies — small files stored on your device (computer or mobile device).',
    ),
    _PolicySection(
      title: 'Information Collection and Use',
      body:
          'We collect several different types of information for various purposes to provide and '
          'improve our Service to you.\n\n'
          'Personal Data — while using our Service, we may ask you to provide certain personally '
          'identifiable information ("Personal Data"), including Cookies and Usage Data.\n\n'
          'Usage Data — when you access the Service through a mobile device, we may collect '
          'certain information automatically, including the type of mobile device you use, your '
          'mobile device unique ID, IP address, operating system, browser type, unique device '
          'identifiers and other diagnostic data.\n\n'
          'Tracking & Cookies — we use cookies and similar tracking technologies to track '
          'activity on our Service. Cookies are files with a small amount of data which may '
          'include an anonymous unique identifier. You can instruct your browser to refuse all '
          'cookies or to indicate when a cookie is being sent.\n\n'
          'Types of cookies we use: Session Cookies (to operate the Service), Preference Cookies '
          '(to remember your preferences), Security Cookies (for security purposes).',
    ),
    _PolicySection(
      title: 'Use of Data',
      body:
          'Aviary Canvas uses the collected data for the following purposes:\n\n'
          '• To provide and maintain the Service\n'
          '• To notify you about changes to our Service\n'
          '• To allow you to participate in interactive features\n'
          '• To provide customer care and support\n'
          '• To provide analysis or valuable information to improve the Service\n'
          '• To monitor the usage of the Service\n'
          '• To detect, prevent and address technical issues',
    ),
    _PolicySection(
      title: 'Transfer of Data',
      body:
          'Your information, including Personal Data, may be transferred to and maintained on '
          'computers located outside of your state, province, country or other governmental '
          'jurisdiction where the data protection laws may differ from those of your jurisdiction. '
          'If you are located outside Seychelles and choose to provide information to us, please '
          'note that we transfer the data, including Personal Data, to Seychelles and process it '
          'there. Your consent to this Privacy Policy followed by your submission of such '
          'information represents your agreement to that transfer. The Service will take all steps '
          'reasonably necessary to ensure that your data is treated securely.',
    ),
    _PolicySection(
      title: 'Disclosure of Data',
      body:
          'The Service may disclose your Personal Data in the good faith belief that such action '
          'is necessary to:\n\n'
          '• Comply with a legal obligation\n'
          '• Protect and defend the rights or property of the Service\n'
          '• Prevent or investigate possible wrongdoing in connection with the Service\n'
          '• Protect the personal safety of users of the Service or the public\n'
          '• Protect against legal liability\n\n'
          'As a European citizen, under GDPR, you have certain individual rights. You can learn '
          'more in the GDPR Guide.',
    ),
    _PolicySection(
      title: 'Security of Data',
      body:
          'The security of your data is important to us, but remember that no method of '
          'transmission over the Internet or method of electronic storage is 100% secure. While '
          'we strive to use commercially acceptable means to protect your Personal Data, we '
          'cannot guarantee its absolute security.',
    ),
    _PolicySection(
      title: 'Service Providers',
      body:
          'We may employ third party companies and individuals to facilitate our Service '
          '("Service Providers"), to provide the Service on our behalf, to perform '
          'Service-related services or to assist us in analyzing how our Service is used. '
          'These third parties have access to your Personal Data only to perform these tasks '
          'on our behalf and are obligated not to disclose or use it for any other purpose.',
    ),
    _PolicySection(
      title: 'Links to Other Sites',
      body:
          'Our Service may contain links to other sites that are not operated by us. If you '
          'click a third party link, you will be directed to that third party\'s site. We '
          'strongly advise you to review the Privacy Policy of every site you visit. We have '
          'no control over and assume no responsibility for the content, privacy policies or '
          'practices of any third party sites or services.',
    ),
    _PolicySection(
      title: "Children's Privacy",
      body:
          'Our Service does not address anyone under the age of 18 ("Children"). We do not '
          'knowingly collect personally identifiable information from anyone under the age of 18. '
          'If you are a parent or guardian and you are aware that your child has provided us with '
          'Personal Data, please contact us. If we become aware that we have collected Personal '
          'Data from children without verification of parental consent, we take steps to remove '
          'that information from our servers.',
    ),
    _PolicySection(
      title: 'Changes to This Privacy Policy',
      body:
          'We may update our Privacy Policy from time to time. We will notify you of any changes '
          'by posting the new Privacy Policy on this page. We will let you know via email and/or '
          'a prominent notice on our Service, prior to the change becoming effective and update '
          'the "effective date" at the top of this Privacy Policy. You are advised to review this '
          'Privacy Policy periodically for any changes. Changes to this Privacy Policy are '
          'effective when they are posted on this page.',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    final safeBottom = MediaQuery.of(context).padding.bottom;

    return CupertinoPageScaffold(
      backgroundColor: AppColors.background,
      child: Stack(
        children: [
          // Subtle animated background gradient
          const _BackgroundGlow(),

          // Content
          CustomScrollView(
            slivers: [
              // Navigation bar
              CupertinoSliverNavigationBar(
                backgroundColor: AppColors.background.withOpacity(0.92),
                border: Border(
                  bottom: BorderSide(color: AppColors.border, width: 0.5),
                ),
                largeTitle: Text(
                  'Privacy Policy',
                  style: AppTextStyles.rankTitle.copyWith(fontSize: 28),
                ),
                leading: CupertinoButton(
                  padding: EdgeInsets.zero,
                  onPressed: () => Navigator.of(context).pop(),
                  child: const Icon(
                    CupertinoIcons.back,
                    color: AppColors.primary,
                  ),
                ),
              ),

              // Body sections
              SliverPadding(
                padding: EdgeInsets.fromLTRB(20, 8, 20, safeBottom + 32),
                sliver: SliverList(
                  delegate: SliverChildBuilderDelegate(
                    (context, index) {
                      final section = _sections[index];
                      return _SectionCard(section: section, index: index);
                    },
                    childCount: _sections.length,
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

// ── Background glow ───────────────────────────────────────────────────────────

class _BackgroundGlow extends StatefulWidget {
  const _BackgroundGlow();

  @override
  State<_BackgroundGlow> createState() => _BackgroundGlowState();
}

class _BackgroundGlowState extends State<_BackgroundGlow>
    with SingleTickerProviderStateMixin {
  late AnimationController _ctrl;
  late Animation<double>   _anim;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
      vsync:    this,
      duration: const Duration(seconds: 6),
    )..repeat(reverse: true);
    _anim = CurvedAnimation(parent: _ctrl, curve: Curves.easeInOut);
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _anim,
      builder: (_, __) => Container(
        decoration: BoxDecoration(
          gradient: RadialGradient(
            center: Alignment(-0.6 + _anim.value * 0.4, -0.8),
            radius: 1.4,
            colors: [
              AppColors.secondary.withOpacity(0.06 + _anim.value * 0.04),
              AppColors.background,
            ],
          ),
        ),
      ),
    );
  }
}

// ── Section card ──────────────────────────────────────────────────────────────

class _SectionCard extends StatelessWidget {
  final _PolicySection section;
  final int            index;
  const _SectionCard({required this.section, required this.index});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: Container(
        padding:    const EdgeInsets.all(18),
        decoration: BoxDecoration(
          color:        AppColors.surface,
          borderRadius: BorderRadius.circular(16),
          border:       Border.all(color: AppColors.border),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (section.title != null) ...[
              Text(
                section.title!,
                style: AppTextStyles.heading3.copyWith(
                  color: AppColors.secondary,
                ),
              ),
              const SizedBox(height: 10),
            ],
            Text(
              section.body,
              style: AppTextStyles.bodySecondary.copyWith(
                height: 1.6,
              ),
            ),
          ],
        ),
      ),
    )
        .animate()
        .fadeIn(delay: (index * 40).ms, duration: 350.ms)
        .slideY(
          begin: 0.05,
          end:   0,
          delay: (index * 40).ms,
          duration: 350.ms,
          curve: Curves.easeOut,
        );
  }
}

// ── Data class ────────────────────────────────────────────────────────────────

class _PolicySection {
  final String? title;
  final String  body;
  const _PolicySection({required this.title, required this.body});
}
